title: Amy Murlowski
domain: amymurlowski.github.io
description: >-
  Amy Murlowski Bio, resume and projects
baseurl: ""
url: "https://amymurlowski.github.io"

# Build settings
markdown: kramdown
remote_theme: eliottvincent/bay
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

header:
  pages:
    - name: Home
      slug: /
    - name: DNP Project
      slug: /dnpproject
    - name: Resume
      slug: /resume

footer:
  contact:
    - name: Email
      value: amy.murlowski@gmail.com
    - name: Email
      value: amurlowski@unmc.edu
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/amy-murlowski-82963332
