title: Amy Murlowski, BSN, RN
domain: amymurlowski.github.io
description: >-
  Doctorate of Nursing Practice Student, focusing on clinical infrastructure and overall practice readiness for patients of size.
baseurl: ""
url: "https://amymurlowski.github.io"

# Build settings
markdown: kramdown
theme: bay_jekyll_theme

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

header:
  pages:
    - name: Home
      slug: /
    - name: Resume
      slug: /resume
    - name: Education & Clinical Experience
      slug: /education
    - name: Scholarly Works
      slug: /scholarly
    - name: Letters of Recommendation
      slug: /recommendations

footer:
  contact:
    - type: email
      name: amy.murlowski@gmail.com
      value: amy.murlowski@gmail.com
    - type: email
      name: amurlowski@unmc.edu
      value: amurlowski@unmc.edu
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/amy-murlowski-82963332

